[variables]
    NODE_VERSION = "20"

[phases.build]
    cmds = [
        "npm ci",
        "npx prisma generate",
        "npx prisma db push"
    ]

[phases.start]
    cmd = "npm start"

[staticAssets]
    "/client" = "./client"