/**
 * Application Constants
 * Default form values and other constants used across the application
 */

export const DEFAULT_FORMS = {
  biochar: {
    experimentNumber: '',
    testOrder: '',
    experimentDate: '',
    dateUnknown: false,
    researchTeam: 'Curia - Germany',
    reactor: '',
    rawMaterial: '',
    startingAmount: '',
    acidAmount: '',
    acidConcentration: '',
    acidMolarity: '',
    acidType: '',
    temperature: '',
    time: '',
    pressureInitial: '',
    pressureFinal: '',
    washAmount: '',
    washMedium: '',
    output: '',
    dryingTemp: '',
    kftPercentage: '',
    comments: ''
  },
  graphene: {
    experimentNumber: '',
    titleNote: '',
    testOrder: '',
    experimentDate: '',
    dateUnknown: false,
    researchTeam: 'Curia - Germany',
    oven: '',
    quantity: '',
    biocharExperiment: '',
    biocharLotNumber: '',
    biocharSource: '',
    baseAmount: '',
    baseType: '',
    baseConcentration: '',
    base2Amount: '',
    base2Type: '',
    base2Concentration: '',
    grindingMethod: '',
    grindingCount: '',
    grindingTime: '',
    grindingFrequency: '',
    homogeneous: '',
    gas: '',
    tempRate: '',
    tempMax: '',
    time: '',
    washAmount: '',
    washSolution: '',
    washConcentration: '',
    washWater: '',
    dryingTemp: '',
    dryingAtmosphere: '',
    dryingPressure: 'atm. Pressure',
    volumeMl: '',
    species: '',
    appearanceTags: [],
    semReportFile: null,
    removeSemReport: false,
    replaceSemReport: false,
    objective: '',
    experimentDetails: '',
    result: '',
    conclusion: '',
    recommendedAction: '',
    objectivePaste: '', // For the paste textarea
    updateReportIds: [],
    output: '',
    comments: ''
  },
  bet: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    mass: '',
    researchTeam: 'Curia - Germany',
    testingLab: 'Fraunhofer-Institut',
    multipointBetArea: '',
    langmuirSurfaceArea: '',
    betReportFile: null,
    removeBetReport: false,
    replaceBetReport: false,
    comments: ''
  },
  conductivity: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    name: '',
    description: '',
    conductivity1kN: '',
    conductivity8kN: '',
    conductivity12kN: '',
    conductivity20kN: '',
    comments: '',
    conductivityReportPath: '',
    conductivityReportFile: null,
    removeConductivityReport: false
  },
  raman: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    researchTeam: 'Curia - Germany',
    testingLab: '',
    // Integration range row (low and high for each)
    integrationRange2DLow: '',
    integrationRange2DHigh: '',
    integrationRangeGLow: '',
    integrationRangeGHigh: '',
    integrationRangeDLow: '',
    integrationRangeDHigh: '',
    integrationRangeDGLow: '',
    integrationRangeDGHigh: '',
    // Integral Typ A row (two values for each)
    integralTypA2D1: '',
    integralTypA2D2: '',
    integralTypAG1: '',
    integralTypAG2: '',
    integralTypAD1: '',
    integralTypAD2: '',
    integralTypADG1: '',
    integralTypADG2: '',
    // Peak high Typ J row (two values for each)
    peakHighTypJ2D1: '',
    peakHighTypJ2D2: '',
    peakHighTypJG1: '',
    peakHighTypJG2: '',
    peakHighTypJD1: '',
    peakHighTypJD2: '',
    peakHighTypJDG1: '',
    peakHighTypJDG2: '',
    ramanReportFile: null,
    removeRamanReport: false,
    replaceRamanReport: false,
    comments: ''
  },
  tem: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    researchTeam: 'Curia - Germany',
    testingLab: '',
    temReportFile: null,
    removeTEMReport: false,
    replaceTEMReport: false,
    comments: ''
  },
  combine: {
    lotNumber: '',
    lotName: '',
    description: ''
  },
  updateReport: {
    description: '',
    weekOf: '',
    grapheneIds: [],
    compoundBatchIds: [],
    updateFile: null
  },
  semReport: {
    reportDate: '',
    grapheneIds: [],
    compoundBatchIds: [],
    semFiles: null
  },
  compoundBatch: {
    batchNumber: '',
    batchName: '',
    createdDate: '',
    dateUnknown: false,
    totalOutput: '',
    description: '',
    experimentIds: []
  },
  shipment: {
    shipmentNumber: '',
    shipFromLocation: 'Curia Frankfurt',
    shipToLocation: '',
    shipmentDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    micronizationSku: '',
    amountShipped: '',
    unit: 'g',
    purpose: '',
    status: 'shipped',
    comments: ''
  },
  micronization: {
    micronizationNumber: '',
    date: '',
    dateUnknown: false,
    skuSuffix: '',  // Changed from sku to skuSuffix
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    startingMaterialAmount: '',
    recoveredAmount: '',
    grindPressure: '',
    dx50: '',
    micronizationReportFile: null,
    removeMicronizationReport: false,
    replaceMicronizationReport: false
  },
  user: {
    username: '',
    email: '',
    firstName: '',
    lastName: '',
    password: '',
    confirmPassword: '',
    role: '',
    isActive: 'true',
    changePassword: false
  }
};