/**
 * Application Constants
 * Default form values and other constants used across the application
 */

export const TASK_CATEGORY_TAGS = [
  'Fundraising', 'Shareholders', 'Patents', 'Legal',
  'Decks & Graphics', 'Notes & Research', 'Production',
  'Science', 'R&D',
  'Finances', 'Sales', 'Administrative Ops', 'Proforma', 'Web & Marketing'
];

export const TASK_INSTITUTION_TAGS = [
  'Curia', 'NEI', 'SpectraPower', 'GoEco',
  'Positron Magnetics', 'GEIC', 'Apollo', 'EAG'
];

export const DEFAULT_FORMS = {
  biochar: {
    experimentNumber: '',
    testOrder: '',
    experimentDate: '',
    dateUnknown: false,
    researchTeam: 'Curia - Germany',
    reactor: '',
    rawMaterial: '',
    startingAmount: '',
    acidAmount: '',
    acidConcentration: '',
    acidMolarity: '',
    acidType: '',
    temperature: '',
    time: '',
    pressureInitial: '',
    pressureFinal: '',
    washAmount: '',
    washMedium: '',
    output: '',
    dryingTemp: '',
    kftPercentage: '',
    comments: ''
  },
  graphene: {
    experimentNumber: '',
    titleNote: '',
    testOrder: '',
    experimentDate: '',
    dateUnknown: false,
    researchTeam: 'Curia - Germany',
    oven: '',
    quantity: '',
    biocharExperiment: '',
    biocharLotNumber: '',
    biocharSource: '',
    baseAmount: '',
    baseType: '',
    baseConcentration: '',
    base2Amount: '',
    base2Type: '',
    base2Concentration: '',
    grindingMethod: '',
    grindingCount: '',
    grindingTime: '',
    grindingFrequency: '',
    homogeneous: '',
    gas: '',
    tempRate: '',
    tempMax: '',
    time: '',
    washAmount: '',
    washSolution: '',
    washConcentration: '',
    washWater: '',
    dryingTemp: '',
    dryingAtmosphere: '',
    dryingPressure: 'atm. Pressure',
    volumeMl: '',
    species: '',
    appearanceTags: [],
    semReportFile: null,
    removeSemReport: false,
    replaceSemReport: false,
    objective: '',
    experimentDetails: '',
    result: '',
    conclusion: '',
    recommendedAction: '',
    objectivePaste: '', // For the paste textarea
    updateReportIds: [],
    output: '',
    comments: ''
  },
  bet: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    mass: '',
    researchTeam: 'Curia - Germany',
    testingLab: 'Fraunhofer-Institut',
    multipointBetArea: '',
    langmuirSurfaceArea: '',
    betReportFile: null,
    removeBetReport: false,
    replaceBetReport: false,
    comments: ''
  },
  conductivity: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    name: '',
    description: '',
    conductivity1kN: '',
    conductivity8kN: '',
    conductivity12kN: '',
    conductivity20kN: '',
    comments: '',
    conductivityReportPath: '',
    conductivityReportFile: null,
    removeConductivityReport: false
  },
  raman: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    researchTeam: 'Curia - Germany',
    testingLab: '',
    // Integration range row (low and high for each)
    integrationRange2DLow: '',
    integrationRange2DHigh: '',
    integrationRangeGLow: '',
    integrationRangeGHigh: '',
    integrationRangeDLow: '',
    integrationRangeDHigh: '',
    integrationRangeDGLow: '',
    integrationRangeDGHigh: '',
    // Integral Typ A row (two values for each)
    integralTypA2D1: '',
    integralTypA2D2: '',
    integralTypAG1: '',
    integralTypAG2: '',
    integralTypAD1: '',
    integralTypAD2: '',
    integralTypADG1: '',
    integralTypADG2: '',
    // Peak high Typ J row (two values for each)
    peakHighTypJ2D1: '',
    peakHighTypJ2D2: '',
    peakHighTypJG1: '',
    peakHighTypJG2: '',
    peakHighTypJD1: '',
    peakHighTypJD2: '',
    peakHighTypJDG1: '',
    peakHighTypJDG2: '',
    ramanReportFile: null,
    removeRamanReport: false,
    replaceRamanReport: false,
    comments: ''
  },
  tem: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    researchTeam: 'Curia - Germany',
    testingLab: '',
    temReportFile: null,
    removeTEMReport: false,
    replaceTEMReport: false,
    comments: ''
  },
  particleSize: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    micronizationSku: '',
    mcbNumber: '',
    d10: '',
    d50: '',
    d90: '',
    meanSize: '',
    spanValue: '',
    testingLab: '',
    testingMethod: '',
    particleSizeReportFile: null,
    removeParticleSizeReport: false,
    replaceParticleSizeReport: false,
    comments: ''
  },
  xrd: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    micronizationSku: '',
    mcbNumber: '',
    peak1_position: '',
    peak1_assignment: '',
    peak2_position: '',
    peak2_assignment: '',
    crystallite_size: '',
    testingLab: '',
    xrdReportFiles: [],
    removeFileIndices: [],
    comments: ''
  },
  xps: {
    testDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    micronizationSku: '',
    mcbNumber: '',
    c1s_percent: '',
    c1s_percent_error: '',
    cl2p_percent: '',
    cl2p_percent_error: '',
    mo3d_percent: '',
    mo3d_percent_error: '',
    n1s_percent: '',
    n1s_percent_error: '',
    o1s_percent: '',
    o1s_percent_error: '',
    s2p_percent: '',
    s2p_percent_error: '',
    si2p_percent: '',
    si2p_percent_error: '',
    c1s_cc_percent: '',
    c1s_cc_error: '',
    c1s_co_percent: '',
    c1s_co_error: '',
    c1s_ceo_percent: '',
    c1s_ceo_error: '',
    c1s_co3_percent: '',
    c1s_co3_error: '',
    c1s_oceo_percent: '',
    c1s_oceo_error: '',
    c1s_sp2_percent: '',
    c1s_sp2_error: '',
    testingLab: '',
    xpsReportFiles: [],
    removeFileIndices: [],
    comments: ''
  },
  combine: {
    lotNumber: '',
    lotName: '',
    description: ''
  },
  updateReport: {
    description: '',
    weekOf: '',
    grapheneIds: [],
    compoundBatchIds: [],
    updateFile: null
  },
  semReport: {
    reportDate: '',
    grapheneIds: [],
    compoundBatchIds: [],
    semFiles: null
  },
  compoundBatch: {
    batchNumber: '',
    batchName: '',
    createdDate: '',
    dateUnknown: false,
    totalOutput: '',
    description: '',
    experimentIds: []
  },
  shipment: {
    shipmentNumber: '',
    shipFromLocation: 'Curia Frankfurt',
    shipToLocation: '',
    shipmentDate: '',
    dateUnknown: false,
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    micronizationSku: '',
    mcbNumber: '',
    amountShipped: '',
    unit: 'g',
    purpose: '',
    status: 'shipped',
    comments: ''
  },
  micronization: {
    micronizationNumber: '',
    date: '',
    dateUnknown: false,
    skuSuffix: '',  // Changed from sku to skuSuffix
    materialType: 'graphene',
    grapheneSample: '',
    compoundBatchNumber: '',
    startingMaterialAmount: '',
    recoveredAmount: '',
    grindPressure: '',
    dx50: '',
    micronizationReportFile: null,
    removeMicronizationReport: false,
    replaceMicronizationReport: false
  },
  mcb: {
    mcbNumber: '',
    mcbLocation: '',
    combinedDate: new Date().toISOString().split('T')[0], // Today's date in YYYY-MM-DD format
    selectedMicronizationIds: [],
    totalRecoveredAmount: 0,
    comments: ''
  },
  user: {
    username: '',
    email: '',
    firstName: '',
    lastName: '',
    password: '',
    confirmPassword: '',
    role: '',
    isActive: 'true',
    changePassword: false
  }
};